name = "vibe-travels"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[site]
bucket = "./dist/client"

[[build.upload]]
format = "service-worker"
dir = "dist"
main = "./dist/server/entry.mjs" 
