name = "vibe-travels"
compatibility_date = "2024-03-11"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[site]
bucket = "./dist/client"

[[build.upload]]
format = "modules"
main = "./dist/_worker.js"
dir = "dist" 
